<a href="https://colab.research.google.com/github/sakuku/Computer_vision/blob/main/GEBRU_SABA_AAI6620_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Assignment 1: Setting Up Python NLP Tools and Building a Basic Text Processing Pipeline

**Course:** Applied NLP  
**Submission:** Upload `Lab_1.ipynb` to Canvas with all cells run and outputs visible.

---

## Overview

In this lab you will set up the core Python libraries used throughout this course and build a basic text analysis pipeline from scratch. You will work with NumPy for numerical operations on text feature data, pandas for loading and manipulating a text dataset, and NLTK for computing frequency statistics over a corpus.

The dataset is a small collection of product reviews. This domain is intentionally simple so that you can focus on the mechanics of the tools rather than the subject matter. These same tools and patterns will appear in every module of the course.

---

## Learning Objectives

By the end of this lab you will be able to:

1. Set up a working Python NLP environment using NumPy, pandas, and NLTK
2. Use NumPy for efficient numerical operations on text feature data
3. Load, inspect, and manipulate a text dataset using pandas
4. Compute a frequency distribution for an NLP corpus using NLTK

---

## Grading

| Component | Points | Method |
|---|---|---|
| Part 1 — NumPy operations | 22 | Autograded |
| Part 2 — pandas operations | 30 | Autograded |
| Part 3 — NLTK frequency analysis | 23 | Autograded |
| Code quality | 25 | Manual review |
| **Total** | **100** | |

### Manual grading rubric (25 points)

The following criteria are assessed by your instructor. These are the professional standards expected of a working data scientist, MLOps engineer, or NLP practitioner. **A note on expectations:** the bar for manual grading rises as the course progresses. You may receive full or near-full marks on these criteria in Lab 1 even with minor gaps — but the same gaps will result in deductions in later labs. Build good habits now.

| Criterion | Points | What we look for |
|---|---|---|
| Docstrings and inline comments | 6 | Every function has a docstring describing purpose, parameters, and return value. Non-obvious logic has a brief comment. Trivial lines do not need comments. |
| Function design | 6 | Logic is wrapped in reusable functions with clear inputs and outputs. No values that should be parameters are hard-coded inside functions. Each function does one thing. |
| Defensive coding | 5 | Basic input validation or type checking where it matters. Code does not silently fail on unexpected input. This matters for pipeline stability. |
| Code clarity and naming | 4 | Variable and function names are descriptive and self-documenting. No single-letter names outside of tight loops. Code reads like a narrative, not a transcript. |
| Avoiding redundancy | 4 | No copy-pasted logic that should be a function. No unnecessary intermediate variables. Apply the DRY (Don't Repeat Yourself) principle proportionally. |

---

## Setup

Run the cell below to install and verify your environment. In Google Colab, NLTK is pre-installed but the corpora must be downloaded each session.

In [24]:
# Setup — run this cell first every session
# It installs any missing packages and downloads the NLTK data needed for this lab.

import subprocess, sys

def install_if_missing(package):
    """Install a package if it cannot be imported.

    Args:
        package (str): The package name to check and install.
    """
    try:
        __import__(package)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package, "-q"])

install_if_missing("numpy")
install_if_missing("pandas")
install_if_missing("nltk")

import numpy as np
import pandas as pd
import nltk

# Download required NLTK resources
for resource in ["punkt", "punkt_tab", "stopwords", "brown"]:
    nltk.download(resource, quiet=True)

print("Environment ready.")
print(f"  numpy  {np.__version__}")
print(f"  pandas {pd.__version__}")
print(f"  nltk   {nltk.__version__}")

Environment ready.
  numpy  2.1.3
  pandas 2.2.3
  nltk   3.9.1

---

## Part 1 — NumPy: Numerical Operations on Text Feature Data (22 points)

NumPy is the numerical backbone of the Python data science stack. In NLP, you will use it constantly to work with arrays of feature values — word counts, TF-IDF scores, embeddings, and more.

In this part you will work with the `rating` and `helpful_votes` columns from the review dataset as NumPy arrays. Each task asks you to produce a specific named variable. The autograder checks those variable names, so use them exactly as specified.

### 1.1 — Load the dataset and extract arrays

Run the cell below to load the review dataset. You do not need to modify it.

In [25]:
# Dataset — do not modify this cell.
# This is a small collection of product reviews used throughout the lab.

import io

REVIEWS_CSV = """review_id,text,rating,category,helpful_votes
1,Great sound quality and comfortable fit,5,electronics,42
2,Stopped working after two weeks,1,electronics,88
3,Exactly as described fast shipping,4,books,15
4,Poor build quality feels cheap,2,home,31
5,Absolutely love this product highly recommend,5,clothing,67
6,Instructions were confusing but product works,3,home,22
7,Battery life is impressive lasts all day,5,electronics,54
8,Returned immediately not as pictured,1,clothing,93
9,Good value for the price,4,books,18
10,Fits perfectly true to size,5,clothing,29
11,Broke on first use very disappointed,1,home,71
12,Decent quality nothing special,3,electronics,8
13,Beautifully written compelling story,5,books,45
14,Too small even for the size listed,2,clothing,37
15,Works as expected no complaints,4,home,12
16,Overpriced for what you get,2,electronics,60
17,Couldnt put it down finished in one sitting,5,books,83
18,Delivery was fast packaging was damaged,3,home,26
19,Great gift idea well received,4,clothing,19
20,Sound cuts out randomly frustrating,2,electronics,48
"""

df = pd.read_csv(io.StringIO(REVIEWS_CSV))
print(f"Loaded {len(df)} reviews across {df['category'].nunique()} categories.")
df.head()

Loaded 20 reviews across 4 categories.

,review_id,text,rating,category,helpful_votes
0,1,Great sound quality and comfortable fit,5,electronics,42
1,2,Stopped working after two weeks,1,electronics,88
2,3,Exactly as described fast shipping,4,books,15
3,4,Poor build quality feels cheap,2,home,31
4,5,Absolutely love this product highly recommend,5,clothing,67

### 1.2 — Create NumPy arrays

Extract the `rating` and `helpful_votes` columns as NumPy arrays.

**Your task:** Complete the function below and call it to produce `ratings_array` and `helpful_array`.

In [26]:
def extract_arrays(dataframe, col_a, col_b):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    array_a = dataframe[col_a].to_numpy()
    array_b = dataframe[col_b].to_numpy()
    return array_a, array_b
    pass

ratings_array, helpful_array = extract_arrays(df, 'rating', 'helpful_votes')

# Verify
print(f"ratings_array: {ratings_array}")
print(f"helpful_array: {helpful_array}")
print(f"dtype: {ratings_array.dtype}, shape: {ratings_array.shape}")

ratings_array: [5 1 4 2 5 3 5 1 4 5 1 3 5 2 4 2 5 3 4 2]
helpful_array: [42 88 15 31 67 22 54 93 18 29 71  8 45 37 12 60 83 26 19 48]
dtype: int64, shape: (20,)

### 1.3 — Summary statistics

Compute basic statistics on `ratings_array` using NumPy methods.

**Your task:** Complete the function and produce the named variables below.

In [27]:
def compute_array_stats(arr):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — return total_ratings, mean_rating

    total_ratings = np.sum(arr)
    mean_rating = np.mean(arr)
    return total_ratings, mean_rating
    pass

total_ratings, mean_rating = compute_array_stats(ratings_array)

print(f"total_ratings: {total_ratings}")
print(f"mean_rating:   {mean_rating}")

total_ratings: 66
mean_rating:   3.3

### 1.4 — Normalization

Normalize `ratings_array` so that all values fall in the range [0, 1] by dividing by the maximum value.

**Your task:** Complete the function and produce `normalized_ratings`.

In [28]:
def normalize_array(arr):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return (arr - arr.min()) / (arr.max() - arr.min())
    pass

normalized_ratings = normalize_array(ratings_array)

print(f"normalized_ratings: {normalized_ratings}")
print(f"min: {normalized_ratings.min():.4f}, max: {normalized_ratings.max():.4f}")

normalized_ratings: [1.   0.   0.75 0.25 1.   0.5  1.   0.   0.75 1.   0.   0.5  1.   0.25
 0.75 0.25 1.   0.5  0.75 0.25]
min: 0.0000, max: 1.0000

### 1.5 — Boolean masking and filtering

Identify reviews whose rating is above a given threshold and extract them.

**Your task:** Complete the two functions below. Produce `above_threshold_mask` and `filtered_ratings`.

In [29]:
RATING_THRESHOLD = 3  # do not change

def make_threshold_mask(arr, threshold):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return arr > threshold
    pass

def apply_mask(arr, mask):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return arr [mask]
    pass

above_threshold_mask = make_threshold_mask(ratings_array, RATING_THRESHOLD)
filtered_ratings = apply_mask(ratings_array, above_threshold_mask)

print(f"Mask:     {above_threshold_mask}")
print(f"filtered_ratings: {filtered_ratings}")
print(f"Count above threshold: {filtered_ratings.size}")

Mask:     [ True False  True False  True False  True False  True  True False False
  True False  True False  True False  True False]
filtered_ratings: [5 4 5 5 4 5 5 4 5 4]
Count above threshold: 10

### 1.6 — Correlation

Compute the Pearson correlation between `ratings_array` and `helpful_array`. This tells you whether higher-rated reviews tend to receive more helpful votes (or fewer).

**Your task:** Complete the function and produce `ratings_helpful_corr`. Round to 4 decimal places.

In [30]:
def compute_correlation(arr_a, arr_b):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — use np.corrcoef
    return np.corrcoef(arr_a, arr_b)[0, 1]
    pass

ratings_helpful_corr = compute_correlation(ratings_array, helpful_array)

print(f"Pearson correlation (rating vs helpful_votes): {ratings_helpful_corr}")
print("Interpretation: ", end="")
if ratings_helpful_corr > 0.1:
    print("Higher-rated reviews tend to get more helpful votes.")
elif ratings_helpful_corr < -0.1:
    print("Lower-rated reviews tend to get more helpful votes.")
else:
    print("No strong linear relationship.")

Pearson correlation (rating vs helpful_votes): -0.31675539655256285
Interpretation: Lower-rated reviews tend to get more helpful votes.

---

## Part 2 — pandas: Loading and Manipulating a Text Dataset (30 points)

pandas is the standard tool for loading, inspecting, and wrangling text datasets before they enter an NLP pipeline. In this part you will perform a series of operations on the same review dataset, producing named variables that the autograder will check.

### 2.1 — Inspect the DataFrame

In [31]:
def inspect_dataframe(dataframe):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — return the shape as a tuple
    return dataframe.shape
    pass

df_shape = inspect_dataframe(df)

print(f"df_shape: {df_shape}")
print(f"\nColumn dtypes:")
print(df.dtypes)
print(f"\nFirst 3 rows:")
df.head(3)

df_shape: (20, 5)

Column dtypes:
review_id         int64
text             object
rating            int64
category         object
helpful_votes     int64
dtype: object

First 3 rows:

,review_id,text,rating,category,helpful_votes
0,1,Great sound quality and comfortable fit,5,electronics,42
1,2,Stopped working after two weeks,1,electronics,88
2,3,Exactly as described fast shipping,4,books,15

### 2.2 — Add a text length column

Character length is one of the simplest text features and a useful sanity check on your data. Add a new column called `text_length` to `df` containing the character count of each review text.

**Your task:** Complete the function. It should modify `df` in place (or return a modified copy — your design choice, but be consistent).

In [32]:
def add_text_length_column(dataframe, text_col):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — add a 'text_length' column
    dataframe['text_length'] = dataframe[text_col].str.len()
    pass

add_text_length_column(df, 'text')

print(df[['text', 'text_length']].head(5))

                                            text  text_length
0        Great sound quality and comfortable fit           39
1                Stopped working after two weeks           31
2             Exactly as described fast shipping           34
3                 Poor build quality feels cheap           30
4  Absolutely love this product highly recommend           45

### 2.3 — Mean text length

Compute the mean text length across all reviews, rounded to 2 decimal places.

**Your task:** Produce `mean_text_length`.

In [33]:
def compute_mean_text_length(dataframe, length_col):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return dataframe[length_col].mean()
    pass

mean_text_length = compute_mean_text_length(df, 'text_length')

print(f"mean_text_length: {mean_text_length}")

mean_text_length: 34.55

### 2.4 — Longest review

Find the text of the review with the highest character count.

**Your task:** Produce `longest_review` (the text string, not the row).

In [34]:
def find_longest_text(dataframe, text_col, length_col):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    longest_index = dataframe[length_col].idxmax()
    return dataframe.loc[longest_index, text_col]
    pass

longest_review = find_longest_text(df, 'text', 'text_length')

print(f"longest_review: '{longest_review}'")
print(f"length: {len(longest_review)} characters")

longest_review: 'Absolutely love this product highly recommend'
length: 45 characters

### 2.5 — Category counts

Count how many reviews belong to each category.

**Your task:** Produce `category_counts` as a pandas Series sorted in descending order.

In [35]:
def count_by_category(dataframe, category_col):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — use value_counts()
    return dataframe[category_col].value_counts()
    pass

category_counts = count_by_category(df, 'category')

print("category_counts:")
print(category_counts)

category_counts:
category
electronics    6
home           5
clothing       5
books          4
Name: count, dtype: int64

### 2.6 — Filter by text length

Return a filtered DataFrame containing only reviews whose text is longer than a given threshold.

**Your task:** Complete the function and produce `long_reviews_df`.

In [36]:
LENGTH_THRESHOLD = 35  # do not change

def filter_by_length(dataframe, length_col, threshold):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return dataframe[dataframe[length_col] > threshold]
    pass

long_reviews_df = filter_by_length(df, 'text_length', LENGTH_THRESHOLD)

print(f"Reviews with text_length > {LENGTH_THRESHOLD}: {len(long_reviews_df)}")
long_reviews_df[['text', 'text_length', 'rating']].head()

Reviews with text_length > 35: 9

                                            text  text_length  rating
0        Great sound quality and comfortable fit           39       5
4  Absolutely love this product highly recommend           45       5
5  Instructions were confusing but product works           45       3
6       Battery life is impressive lasts all day           40       5
7           Returned immediately not as pictured           36       1

### 2.7 — Filter by rating

Return a filtered DataFrame containing only reviews with a rating at or above a given threshold.

**Your task:** Complete the function and produce `high_rated_df`.

In [37]:
RATING_FILTER = 4  # do not change

def filter_by_rating(dataframe, rating_col, min_rating):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return dataframe[dataframe[rating_col] >= min_rating]
    pass

high_rated_df = filter_by_rating(df, 'rating', RATING_FILTER)

print(f"Reviews with rating >= {RATING_FILTER}: {len(high_rated_df)}")
high_rated_df[['text', 'rating', 'category']].head()

Reviews with rating >= 4: 10

                                            text  rating     category
0        Great sound quality and comfortable fit       5  electronics
2             Exactly as described fast shipping       4        books
4  Absolutely love this product highly recommend       5     clothing
6       Battery life is impressive lasts all day       5  electronics
8                       Good value for the price       4        books

### 2.8 — Average rating by category

Compute the mean rating for each category, rounded to 2 decimal places, sorted from highest to lowest.

**Your task:** Produce `avg_rating_by_category` as a pandas Series.

In [38]:
def avg_rating_by_group(dataframe, group_col, rating_col):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — use groupby
    return dataframe.groupby(group_col)[rating_col].mean()
    pass

avg_rating_by_category = avg_rating_by_group(df, 'category', 'rating')

print("avg_rating_by_category:")
print(avg_rating_by_category)

avg_rating_by_category:
category
books          4.5
clothing       3.4
electronics    3.0
home           2.6
Name: rating, dtype: float64

---

## Part 3 — NLTK: Frequency Distribution over a Corpus (23 points)

A frequency distribution (or FreqDist in NLTK) is one of the most fundamental tools in NLP. It counts how often each word type appears in a text, which underpins everything from basic corpus statistics to TF-IDF and language modeling.

In this part you will work with a excerpt from the Brown corpus — a standard reference corpus included with NLTK — to build a frequency distribution and extract statistics from it.

### 3.1 — Load and tokenize a corpus excerpt

In [39]:
from nltk.corpus import brown
from nltk import FreqDist
from nltk.tokenize import word_tokenize

# We use the 'news' category of the Brown corpus.
# This is a stable, well-known reference corpus.
CORPUS_CATEGORY = 'news'

def load_corpus_tokens(corpus, category):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — return a list of lowercase tokens from brown.words(categories=category)
    return [word.lower() for word in corpus.words(categories=category)]
    pass

corpus_tokens = load_corpus_tokens(brown, CORPUS_CATEGORY)

print(f"Total tokens in '{CORPUS_CATEGORY}' category: {len(corpus_tokens)}")
print(f"First 20 tokens: {corpus_tokens[:20]}")

Total tokens in 'news' category: 100554
First 20 tokens: ['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', "atlanta's", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', "''", 'that']

### 3.2 — Build a frequency distribution

**Your task:** Build an `nltk.FreqDist` from `corpus_tokens` and assign it to `fdist`.

In [40]:
def build_freq_dist(tokens):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — return an nltk.FreqDist
    return FreqDist(tokens)
    pass

fdist = build_freq_dist(corpus_tokens)

print(f"Vocabulary size (unique types): {len(fdist)}")
print(f"Total token count: {fdist.N()}")
print(f"\nMost common 5 words:")
for word, count in fdist.most_common(5):
    print(f"  {word!r:20s} {count:6d}")

Vocabulary size (unique types): 13112
Total token count: 100554

Most common 5 words:
  'the'                  6386
  ','                    5188
  '.'                    4030
  'of'                   2861
  'and'                  2186

### 3.3 — Vocabulary size

**Your task:** Produce `vocab_size` — the number of unique word types in the distribution.

In [41]:
def get_vocab_size(freq_dist):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return len(freq_dist)
    pass

vocab_size = get_vocab_size(fdist)

print(f"vocab_size: {vocab_size}")

vocab_size: 13112

### 3.4 — Top 10 most common words

**Your task:** Produce `top_10_words` — a list of (word, count) tuples for the 10 most frequent tokens.

In [42]:
def get_top_n(freq_dist, n):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — use .most_common(n)
    return freq_dist.most_common(n)
    pass

top_10_words = get_top_n(fdist, 10)

print("top_10_words:")
for word, count in top_10_words:
    print(f"  {word!r:20s} {count:6d}")

top_10_words:
  'the'                  6386
  ','                    5188
  '.'                    4030
  'of'                   2861
  'and'                  2186
  'to'                   2144
  'a'                    2130
  'in'                   2020
  'for'                   969
  'that'                  829

### 3.5 — Hapax legomena

A **hapax legomenon** (plural: hapax legomena) is a word that appears exactly once in the corpus. Hapax legomena make up a large fraction of any natural language corpus and are important for understanding vocabulary coverage and language model challenges.

**Your task:** Produce `hapax_count` — the number of tokens with frequency exactly 1. Use `FreqDist.hapaxes()`.

In [43]:
def count_hapaxes(freq_dist):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE — use freq_dist.hapaxes()
    return len(freq_dist.hapaxes())
    pass

hapax_count = count_hapaxes(fdist)

print(f"hapax_count: {hapax_count}")
print(f"As a fraction of vocabulary: {hapax_count / vocab_size:.1%}")

hapax_count: 6834
As a fraction of vocabulary: 52.1%

### 3.6 — Frequency of a specific word

**Your task:** Complete a function that returns the frequency of any given word in the distribution. Produce `freq_the` for the word `'the'`.

In [44]:
def get_word_frequency(freq_dist, word):
    """YOUR DOCSTRING HERE."""
    # YOUR CODE HERE
    return freq_dist[word]
    pass

freq_the = get_word_frequency(fdist, 'the')

print(f"Frequency of 'the': {freq_the}")
print(f"As a fraction of all tokens: {freq_the / fdist.N():.4f}")

Frequency of 'the': 6386
As a fraction of all tokens: 0.0635

---

## Submission checklist

Before uploading to Canvas:

- [ ] All cells run top-to-bottom without errors (use **Runtime → Run all**)
- [ ] All named variables are defined: `ratings_array`, `helpful_array`, `total_ratings`, `mean_rating`, `normalized_ratings`, `above_threshold_mask`, `filtered_ratings`, `ratings_helpful_corr`, `df_shape`, `mean_text_length`, `longest_review`, `category_counts`, `long_reviews_df`, `high_rated_df`, `avg_rating_by_category`, `corpus_tokens`, `fdist`, `vocab_size`, `top_10_words`, `hapax_count`, `freq_the`
- [ ] Every function has a complete docstring
- [ ] No hard-coded answer values (your functions must compute the answers, not return literals)
- [ ] File is saved as `Lab_1.ipynb`